baseURL = ""
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Good Gaming Community"
theme = "hermit"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
blackfriday = { }
themesDir = "themes"
publishDir = "public"

[author]
name = "Good Gaming Community"

[taxonomies]
tag = "tags"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
themeColor = "#494f5c"
homeSubtitle = "Unsere geliebte Community GGC wird es ab heute, dem 15. Februar 2021 in der bekannten Form nicht mehr geben. Aus Jux und Tollerei kam diese Community zustande und dem Mut einen neuen Ort für viele Persönlichkeiten zu schaffen. Aber auch wir lassen die Kirche im Dorf... unser Projekt  ist nicht so herangewachsen, wie ich oder wir uns das vorgestellt haben. Wir werden daher unsere Dienste mit sofortiger Wirkung einstellen. Ihr habt weiterhin die Möglichkeit mit uns auf dem Teamspeak³ oder dem Rustserver in Kontakt zu treten. Vielen dank für alles! ~ euer Strudi"
footerCopyright = ''
justifyContent = false
relatedPosts = false
code_copy_button = true

  [[menu.main]]
  name = "<a href="ts3server://ts3.hoster.com?port=9987">Click to connect to my</a>TeamSpeak³"
  identifier = "TeamSpeak³"